name: Ruff Lint

on:
  pull_request:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/ruff-lint-on-pr.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check .
